# PIR-RAG Configuration File
# 
# This file contains configuration settings for PIR-RAG experiments.
# Modify these parameters to customize your experiments.

# Data Configuration
data:
  # Path to the embeddings file (relative to project root)
  embeddings_path: "data/embeddings_10000.npy"
  
  # Path to the corpus file (relative to project root)
  corpus_path: "data/corpus_10000.csv"
  
  # Path to the local sentence transformer model
  model_path: "../shared_models/bge_model"
  
  # Pre-processed size-based groups (created by data preparation)
  size_groups:
    small: "data/size_groups/small_lt1500.csv"      # <1500 bytes
    medium_small: "data/size_groups/medium_small_1500_2500.csv"  # 1500-2500 bytes
    medium: "data/size_groups/medium_2500_3500.csv"        # 2500-3500 bytes
    medium_large: "data/size_groups/medium_large_3500_4500.csv"  # 3500-4500 bytes
    large: "data/size_groups/large_gt4500.csv"         # >4500 bytes
  
  # Size group boundaries (in bytes)
  size_boundaries: [1500, 2500, 3500, 4500]

# Default Experiment Parameters
defaults:
  n_clusters: 1000
  key_length: 2048
  top_n_clusters: 3
  n_eval_queries: 100

# Experiment Configurations
experiments:
  
  # Document Size Impact (using pre-processed size groups)
  document_size:
    enabled: true
    size_groups: ["small", "medium_small", "medium", "medium_large", "large"]
    n_docs_per_group: 100               # Fixed number of docs from each size group
    n_eval_queries: 10                  # Queries per size group
    fixed_params:
      n_clusters: 10
      key_length: 1024
      top_n_clusters: 1
  
  # Document Count Impact (using same size group)
  document_count:
    enabled: false  # Set to true to enable
    target_size_group: "medium"         # Use medium size group (2500-3500 bytes)
    doc_counts: [100, 150, 200, 250, 300]  # Different numbers of documents to test
    n_eval_queries: 10                  # Queries per document count
    fixed_params:
      n_clusters: 10                    # Will vary with document count
      key_length: 1024
      top_n_clusters: 1
  
  # Cluster Count Impact
  cluster_count:
    enabled: false  # Set to true to enable
    cluster_counts: [100, 500, 1000, 5000, 10000]
    n_eval_queries: 50
    fixed_params:
      key_length: 2048
      top_n_clusters: 3
  
  # Top-K Clusters Impact
  top_k_clusters:
    enabled: false  # Set to true to enable
    top_k_values: [1, 2, 3, 5, 10]
    n_eval_queries: 50
    fixed_params:
      n_clusters: 1000
      key_length: 2048
  
  # Key Length Impact
  key_length:
    enabled: false  # Set to true to enable
    key_lengths: [1024, 2048, 3072]
    n_eval_queries: 50
    fixed_params:
      n_clusters: 1000
      top_n_clusters: 3

# HPC/SLURM Configuration
slurm:
  job_name: "pir_rag_exp"
  time: "12:00:00"
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 16
  memory: "64G"
  
# Output Configuration
output:
  results_dir: "./results"
  save_intermediate: true
  timestamp_format: "%Y%m%d-%H%M%S"
